### PR TITLE
Fix ConnectionString and update guideline with mongosh client deployment

### LINKED ISSUE #65: Connection string in status does not work
1) Deploy a mongosh pod:
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: mongosh-client
  labels:
    app: mongosh
spec:
  containers:
  - name: mongosh
    image: alpine/mongosh
    command: ["sleep", "infinity"
 EOF
 
2) got to container: kubectl exec -it mongosh-client -- bash
 
3) jrun mongosh: mongosh 'mongodb://k8s_secret_user:K8sSecret100@10.96.185.159:10260/?directConnection=true&authMechanism=SCRAM-SHA-256&tls=true&tlsAllowInvalidCertificates=true&appName=mongosh+2.0.2'
 
 not sure if we add the & stuff or not - depends on if we can get better certs

### PR DESCRIPTION
**Pull request by hossain-rayhan**
Tested with both `LoadBalancer` and `ClusterIP` service type.

```
rhossain@rayhanmsft:~/wsl_workspace/bromine/documentdb-kubernetes-operator$ kubectl exec -it deployment/mongosh-client -n documentdb-preview-ns -- bash
Defaulted container "mongosh-client" out of: mongosh-client, install-kubectl (init)
root@mongosh-client-779b6b5fdc-bw7ql:/# kubectl get documentdb -n documentdb-preview-ns
NAME                 STATUS                     CONNECTION STRING
documentdb-preview   Cluster in healthy state   mongodb://$(kubectl get secret documentdb-credentials -n documentdb-preview-ns -o jsonpath='{.data.username}' | base64 -d):$(kubectl get secret documentdb-credentials -n documentdb-preview-ns -o jsonpath='{.data.password}' | base64 -d)@10.0.66.113:10260/?directConnection=true&authMechanism=SCRAM-SHA-256&tls=true&tlsAllowInvalidCertificates=true&replicaSet=rs0
root@mongosh-client-779b6b5fdc-bw7ql:/# mongosh "mongodb://$(kubectl get secret documentdb-credentials -n documentdb-preview-ns -o jsonpath='{.data.username}' | base64 -d):$(kubectl get secret documentdb-credentials -n documentdb-preview-ns -o jsonpath='{.data.password}' | base64 -d)@10.0.66.113:10260/?directConnection=true&authMechanism=SCRAM-SHA-256&tls=true&tlsAllowInvalidCertificates=true&replicaSet=rs0"
Current Mongosh Log ID: 68892a94b2df9547fc89b03c
Connecting to:          mongodb://<credentials>@10.0.66.113:10260/?directConnection=true&authMechanism=SCRAM-SHA-256&tls=true&tlsAllowInvalidCertificates=true&replicaSet=rs0&appName=mongosh+2.5.6
Using MongoDB:          7.0.0
Using Mongosh:          2.5.6

For mongosh info see: https://www.mongodb.com/docs/mongodb-shell/

rs0 [direct: mongos] test>
```

Fixes #65 and #66

### CODE REVIEW

File: internal/utils/util.go [hunk 1]
```diff
@@ -251,13 +251,6 @@ func DeleteRoleBinding(ctx context.Context, c client.Client, name, namespace str
...
-	return fmt.Sprintf("mongodb://%s:<password>%s:%d/?replicaSet=rs0", documentDbUsername, serviceIp, GetPortFor(GATEWAY_PORT))
-}
-
-func getDocumentDbUsername() string {
-
-	// TODO: Implement logic to retrieve the username from the DocumentDB instance or configuration
-	// For now, we return a default username.
-	return "default_user"
+	// TODO: Update the secret name once its configureable through DocumentDB Spec
+	return fmt.Sprintf("mongodb://$(kubectl get secret documentdb-credentials -n %s -o jsonpath='{.data.username}' | base64 -d):$(kubectl get secret documentdb-credentials -n %s -o jsonpath='{.data.password}' | base64 -d)@%s:%d/?directConnection=true&authMechanism=SCRAM-SHA-256&tls=true&tlsAllowInvalidCertificates=true&replicaSet=rs0", documentdb.Namespace, documentdb.Namespace, serviceIp, GetPortFor(GATEWAY_PORT))
```
Comment (till) [inline internal/utils/util.go:255]: Are you vibecoding this?

**Review by till — CHANGES_REQUESTED** [review]

**Review by xgerman — APPROVED** [review]

File: internal/utils/util.go (hunk 1 above)
Comment (hossain-rayhan) [reply internal/utils/util.go:255]: Using Microsoft Copilot if that counts.
